FROM nginxinc/nginx-unprivileged:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html login.html app.html /usr/share/nginx/html/
COPY assets /usr/share/nginx/html/assets

EXPOSE 8080

